-- Rollback: VISIT_RECORDテーブルの削除
-- このファイルは手動ロールバック用です

-- 外部キー制約を削除
ALTER TABLE `VISIT_RECORD` DROP FOREIGN KEY `FK_VISIT_RECORD_CUSTOMER`;
ALTER TABLE `VISIT_RECORD` DROP FOREIGN KEY `FK_VISIT_RECORD_REPORT`;

-- テーブルを削除
DROP TABLE IF EXISTS `VISIT_RECORD`;
